n = input('Digite um valor: ')
print('Tipo primitivo: ', type(n))
print('É alfanúmerico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('É número? ', n.isnumeric())
print('Esta em minísculas? ', n.islower())
print('Esta em maiúsculas? ', n.isupper())
print('Esta capitalizada? ', n.isascii())
print('Só tem espaços? ', n.istitle())