number = int(input('Digite um número para tabuar: '))
print('-'*12)
print('1x{:2} = {}'.format(number, number*1))
print('2x{:2} = {}'.format(number, number*2))
print('3x{:2} = {}'.format(number, number*3))
print('4x{:2} = {}'.format(number, number*4))
print('5x{:2} = {}'.format(number, number*5))
print('6x{:2} = {}'.format(number, number*6))
print('7x{:2} = {}'.format(number, number*7))
print('8x{:2} = {}'.format(number, number*8))
print('9x{:2} = {}'.format(number, number*9))
print('10x{:2} = {}'.format(number, number*10))
print('-'*12)